[workspace]
members = ["components", "rainmaker", "led_switch"]
resolver = "2"
license = "GPL-3.0-only"

[profile.dev]
opt-level = "z"
debug = true
# lto = true

[profile.release]
opt-level = "z"
strip = true
panic = "abort"
