[workspace]
members = ["components", "rainmaker", "led_switch"]
resolver = "2"
license = "GPL-3.0-only"

[profile.dev]
opt-level = "z"
debug = true

# [profile.release]
# opt-level = "z"
# debug = true
# lto = true
# panic = "abort"
# strip = true
# codegen-units = 1
