[target.riscv32imc-esp-espidf]
runner = "espflash flash --monitor"
linker = "ldproxy"
rustflags = [
    "--cfg", "espidf_time64",
    "-C", "default-linker-libraries"
]

[build]
target = "riscv32imc-esp-espidf"
#target = "x86_64-unknown-linux-gnu"

[unstable]
build-std = ["std", "panic_abort"]