[package]
name = "led_switch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
components = {path="../components"}

[target.'cfg(target_os="linux")'.dependencies]
env_logger = "0.10.1"

[target.'cfg(target_os="espidf")'.dependencies]
esp-idf-svc = "0.47.3"
log = "0.4.20" # used for setting log level

[build-dependencies]
embuild = "0.31.4"
