[package]
name = "led_switch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rainmaker = { path = "../rainmaker" }

[target.'cfg(target_os="espidf")'.dependencies]
esp-idf-svc = { version = "0.47.3", default-features = false, features = ["binstart"] }

[build-dependencies]
embuild = {version = "0.31.4", default-features = false, features = ["espidf"]}
