[package]
name = "rainmaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_components = { path = "../core_components" }

[target.'cfg(target_os="linux")'.dependencies]
simple_logger = "4.3.3"

[target.'cfg(target_os="espidf")'.dependencies]
esp-idf-svc = "0.47.3"