on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # toolchain: 
        #   # - stable
        #   - nightly
        target:
          - riscv32imc-esp-espidf
          # - xtensa-esp32-espidf
          # - xtensa-esp32s2-espidf
          # - xtensa-esp32s3-espidf
        idf-version:
          - v5.2

    steps:
    - uses: actions/checkout@v3

    # - if: matrix.target == 'riscv32imc-esp-espidf' && matrix.toolchain == 'nightly'
    #   uses: dtolnay/rust-toolchain@v1
    #   with:
    #     toolchain: ${{ matrix.toolchain }}
    #     components: rustfmt, clippy, rust-src

    # for now, only test on esp toolchain for all targets(temporarily)

    # - if: matrix.target != 'riscv32imc-esp-espidf'  && matrix.toolchain == 'stable' # run xtensa targets only on stable toolchain
    - name: Setup | Install ESP rust toolchain
      uses: esp-rs/xtensa-toolchain@v1.5.1
      with:
        default: true

    - name: Build | Clippy
      env:
        ESP_IDF_VERSION: ${{ matrix.idf-version }}
      run: cargo clippy --target ${{ matrix.target }} -- -D warnings

    - name: Build | Fmt Check
      run: cargo fmt -- --check
      
      
